spring.application.name=task-service

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
app.cache.redis.enabled=true

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Strategy: statusBasedPriorityStrategy or agePriorityStrategy
app.task.priority.strategy=statusBasedPriorityStrategy

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.use-fqn=true

# Page size defaults
spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=100
